#!/usr/bin/env python3
"""Generate or verify ecosystem pointers to canonical governance rules."""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path, PurePosixPath


def safe_relative(value: object, field: str) -> Path:
    if not isinstance(value, str) or not value:
        raise ValueError(f"{field} must be a non-empty relative path")
    path = PurePosixPath(value)
    if path.is_absolute() or ".." in path.parts:
        raise ValueError(f"{field} must stay inside the repository: {value}")
    return Path(*path.parts)


def load_policy(root: Path, policy_arg: str) -> dict[str, object]:
    policy_path = root / safe_relative(policy_arg, "--policy")
    value = json.loads(policy_path.read_text(encoding="utf-8"))
    if not isinstance(value, dict) or value.get("schema_version") != 1:
        raise ValueError("stub policy must be an object with schema_version=1")
    return value


def strings(policy: dict[str, object], key: str) -> list[str]:
    value = policy.get(key)
    if not isinstance(value, list) or not all(isinstance(item, str) for item in value):
        raise ValueError(f"{key} must be a list of strings")
    return value


def render(source: Path, destination: Path) -> str:
    target = Path(os.path.relpath(source, destination.parent)).as_posix()
    return (
        "<!-- GENERATED by scripts/sync-agent-stubs.py; DO NOT EDIT. -->\n"
        f"# {source.stem}\n\n"
        f"Canonical rule: [{source.as_posix()}]({target}).\n"
    )


BEGIN = "<!-- BEGIN gov-harness: generated by scripts/sync-agent-stubs.py -->"
END = "<!-- END gov-harness -->"


def agents_block(root: Path, canonical_root: Path) -> str:
    """Render the managed AGENTS.md section: pointers only, never content.

    AGENTS.md is read by most agent tools on every task, so this stays short
    and says where the doctrine is rather than restating it. Restating would
    make it a second head of truth and the first copy to rot.
    """
    rules = sorted(
        path.stem for path in (root / canonical_root).glob("*.md") if path.is_file()
    )
    lines = [
        BEGIN,
        "## Working doctrine",
        "",
        f"Rules governing work in this repository live in `{canonical_root.as_posix()}/`.",
        "Read them there; this section is generated and holds no doctrine of its own.",
        "",
    ]
    if rules:
        lines.append(", ".join(f"`{name}`" for name in rules) + ".")
        lines.append("")
    if "spec-home" in rules:
        lines.append(
            f"Requirement truth has exactly one home, named by "
            f"`{(canonical_root / 'spec-home.md').as_posix()}`. Never open a second one."
        )
        lines.append("")
    lines.append("Verify the installed doctrine with `python3 scripts/harness.py check`.")
    lines.append(END)
    return "\n".join(lines) + "\n"


def splice(existing: str, block: str) -> str:
    """Replace the managed block, leaving every other byte of the file alone."""
    start = existing.find(BEGIN)
    if start == -1:
        if not existing:
            return block
        separator = "" if existing.endswith("\n\n") else "\n" if existing.endswith("\n") else "\n\n"
        return existing + separator + block
    end = existing.find(END, start)
    if end == -1:
        raise ValueError(f"AGENTS.md has {BEGIN!r} without its closing marker")
    tail = existing[end + len(END):]
    return existing[:start] + block.rstrip("\n") + tail


def run(root: Path, policy: dict[str, object], write: bool) -> list[str]:
    canonical_root = safe_relative(policy.get("canonical_root"), "canonical_root")
    rules = strings(policy, "rules")
    stub_roots = [
        safe_relative(item, "stub_roots") for item in strings(policy, "stub_roots")
    ]
    findings: list[str] = []

    for rule in rules:
        name = safe_relative(rule, "rules")
        if len(name.parts) != 1 or name.suffix != ".md":
            raise ValueError(f"rule must be a Markdown basename: {rule}")
        source = canonical_root / name
        if not (root / source).is_file():
            findings.append(f"missing canonical rule: {source.as_posix()}")
            continue
        for stub_root in stub_roots:
            destination = stub_root / name
            expected = render(source, destination)
            target = root / destination
            if write:
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(expected, encoding="utf-8")
            elif not target.is_file() or target.read_text(encoding="utf-8") != expected:
                findings.append(f"stale or missing generated stub: {destination.as_posix()}")

    agents_file = policy.get("agents_file")
    if agents_file is not None:
        # AGENTS.md is the cross-tool standard and belongs to the project, so
        # the harness owns a delimited block inside it rather than the file.
        target = root / safe_relative(agents_file, "agents_file")
        expected = splice(
            target.read_text(encoding="utf-8") if target.is_file() else "",
            agents_block(root, canonical_root),
        )
        if write:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(expected, encoding="utf-8")
        elif not target.is_file():
            findings.append(f"missing generated doctrine block: {agents_file}")
        elif target.read_text(encoding="utf-8") != expected:
            findings.append(f"stale generated doctrine block: {agents_file}")

    for item in strings(policy, "forbidden_content_roots"):
        forbidden = root / safe_relative(item, "forbidden_content_roots")
        if forbidden.exists() and any(forbidden.rglob("*.md")):
            findings.append(f"content-bearing duplicate rule home: {item}")
    return findings


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=".")
    parser.add_argument("--policy", default="docs/governance/stub-policy.json")
    parser.add_argument("--write", action="store_true")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])
    root = Path(args.root).resolve()
    try:
        findings = run(root, load_policy(root, args.policy), args.write)
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(
            f"DOC-G3 CONFIG: {exc}; copy "
            "docs/governance/stub-policy.example.json and edit it",
            file=sys.stderr,
        )
        return 2
    for finding in findings:
        print(f"DOC-G3 {finding}")
    if findings:
        return 2
    print("DOC-G3 stubs written" if args.write else "DOC-G3 clean")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
